name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # specify the Node.js version here

      - name: Install dependencies
        run: npm install
        working-directory: amber-website
        
      - name: Build project
        run: npm run build
        working-directory: amber-website


      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: amber-website

 
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "joshdevaney99@gmail.com"
              git config --global user.name "joshdevaney"
                  npm run deploy
                  env: 
                        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

